//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGateway.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoGateway.Service.Resources.ServiceMessages", typeof(ServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} and {1} are not equal.
        /// </summary>
        public static string AreNotEqual {
            get {
                return ResourceManager.GetString("AreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request Result.
        /// </summary>
        public static string BadRequestResult {
            get {
                return ResourceManager.GetString("BadRequestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation email has been sent to you..
        /// </summary>
        public static string ConfirmationEmailSent {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری گرامی، واریز ارزی شما به مقدار {0} {1} در سامانه دیجی بلاکس با موفقیت ثبت گردید..
        /// </summary>
        public static string CustomerDepositIsDoneMessage {
            get {
                return ResourceManager.GetString("CustomerDepositIsDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری گرامی، واریز ارزی شما با مشخصات اعلام شده در سیستم ثبت گردید و در اسرع وقت بررسی می گردد. 
        ///با سپاس فراوان.
        /// </summary>
        public static string CustomerInformMessage {
            get {
                return ResourceManager.GetString("CustomerInformMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed.
        /// </summary>
        public static string EmailIsNotConfirmed {
            get {
                return ResourceManager.GetString("EmailIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Was Confirmed.
        /// </summary>
        public static string EmailWasConfirmed {
            get {
                return ResourceManager.GetString("EmailWasConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity with id {0} cannot be found..
        /// </summary>
        public static string EntityIdNotFound {
            get {
                return ResourceManager.GetString("EntityIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with id {1} cannot be found..
        /// </summary>
        public static string EntityIdNotFoundByName {
            get {
                return ResourceManager.GetString("EntityIdNotFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity with: {0} already exists..
        /// </summary>
        public static string EntityIsExists {
            get {
                return ResourceManager.GetString("EntityIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}: {1} already exists..
        /// </summary>
        public static string EntityIsExistsByEntityName {
            get {
                return ResourceManager.GetString("EntityIsExistsByEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with these parameters already exists..
        /// </summary>
        public static string EntityIsExistsByParameters {
            get {
                return ResourceManager.GetString("EntityIsExistsByParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is invalid..
        /// </summary>
        public static string InvalidByName {
            get {
                return ResourceManager.GetString("InvalidByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Confirmation Request.
        /// </summary>
        public static string InvalidEmailConfirmation {
            get {
                return ResourceManager.GetString("InvalidEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with: {1} is invalid..
        /// </summary>
        public static string InvalidEntityIdByName {
            get {
                return ResourceManager.GetString("InvalidEntityIdByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid External Authentication..
        /// </summary>
        public static string InvalidExternalAuthentication {
            get {
                return ResourceManager.GetString("InvalidExternalAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token Verification.
        /// </summary>
        public static string InvalidTokenVerification {
            get {
                return ResourceManager.GetString("InvalidTokenVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with id {1} is not a crypto currency.
        /// </summary>
        public static string IsNotCrypto {
            get {
                return ResourceManager.GetString("IsNotCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with id {1} is not a fiat currency.
        /// </summary>
        public static string IsNotFiat {
            get {
                return ResourceManager.GetString("IsNotFiat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough credit for {0}.
        /// </summary>
        public static string NotEnoughCredit {
            get {
                return ResourceManager.GetString("NotEnoughCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} : {1} cannot be found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment link creation is currently only possible for Tether..
        /// </summary>
        public static string OnlyTetherIsAllowed {
            get {
                return ResourceManager.GetString("OnlyTetherIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was reset..
        /// </summary>
        public static string PasswordWasReset {
            get {
                return ResourceManager.GetString("PasswordWasReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset password URL has been sent to you..
        /// </summary>
        public static string RestPasswordUrlEmailSent {
            get {
                return ResourceManager.GetString("RestPasswordUrlEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was successful..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Authentication : {0}.
        /// </summary>
        public static string UnauthorizedByParam {
            get {
                return ResourceManager.GetString("UnauthorizedByParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Authentication.
        /// </summary>
        public static string UnauthorizedResult {
            get {
                return ResourceManager.GetString("UnauthorizedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. Please try again later or contact support for assistance..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، واریز ارزی مشتری شما با شناسه {0} و مقدار {1} {2} در سامانه دیجی بلاکس با موفقیت ثبت گردید..
        /// </summary>
        public static string UserDepositIsDoneMessage {
            get {
                return ResourceManager.GetString("UserDepositIsDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an active API key. To create a new API key, you must first delete the previous one..
        /// </summary>
        public static string UserHasActiveApiKey {
            get {
                return ResourceManager.GetString("UserHasActiveApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، مشتری شما با شناسه {0} واریز ارزی خود را اعلام نموده است. 
        ///در اسرع وقت بررسی میگردد. 
        ///با سپاس فراوان.
        /// </summary>
        public static string UserInformMessage {
            get {
                return ResourceManager.GetString("UserInformMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، پرداخت مشتری شما با شناسه {0} و مقدار {1} {2} در سامانه دیجی بلاکس با موفقیت ثبت گردید..
        /// </summary>
        public static string UserPaymentIsDoneMessage {
            get {
                return ResourceManager.GetString("UserPaymentIsDoneMessage", resourceCulture);
            }
        }
    }
}
